jaguar_v2:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  #
  # # Position Controllers ---------------------------------------
  joint_left_flipper_controller:
    type: effort_controllers/JointVelocityController
    joint: left_flipper_to_base_link_joint
    #pid: {p: 400.0, i: 0.01, d: 10.0}
    pid: {p: 10.0, i: 0.01, d: 1.0}

  joint_right_flipper_controller:
    type: effort_controllers/JointVelocityController
    joint: right_flipper_to_base_link_joint
    #pid: {p: 400.0, i: 0.01, d: 10.0}
    pid: {p: 10.0, i: 0.01, d: 1.0}

  #joint_cronstein:
  #    type: effort_controllers/JointPositionController
  #    joint: joint_cronstein
  #    pid: {p: 100.0, i: 0.01, d: 10.0}

  #joint_first_part:
  #  type: effort_controllers/JointPositionController
  #  joint: joint_first_part
  #  pid: {p: 300.0, i: 0.01, d: 10.0}

  #joint_second_part:
  #    type: effort_controllers/JointPositionController
  #    joint: joint_second_part
  #    pid: {p: 600.0, i: 0.01, d: 10.0}

  #joint_head:
  #      type: effort_controllers/JointPositionController
  #      joint: joint_head
  #      pid: {p: 100.0, i: 0.01, d: 10.0}
  #
  #

  # # Velocity Controllers ---------------------------------------
  right:
     type: effort_controllers/JointVelocityController
     joint: right_middle_wheel_to_base_link_joint
     pid: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 10.0}

  left:
     type: effort_controllers/JointVelocityController
     joint: left_middle_wheel_to_base_link_joint
     pid: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 10.0}

  joint_right_rear_base_link_wheel_controller:
     type: effort_controllers/JointVelocityController
     joint: right_rear_wheel_to_base_link_joint
     pid: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 10.0}

  joint_left_rear_base_link_wheel_controller:
     type: effort_controllers/JointVelocityController
     joint: left_rear_wheel_to_base_link_joint
     pid: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 10.0}

  joint_right_flipper_wheel_controller:
     type: effort_controllers/JointVelocityController
     joint: right_flipper_wheel_to_right_flipper_link_joint
     pid: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 10.0}

  joint_left_flipper_wheel_controller:
     type: effort_controllers/JointVelocityController
     joint: left_flipper_wheel_to_left_flipper_link_joint
     pid: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 10.0}

  joint_right_front_base_link_wheel_controller:
     type: effort_controllers/JointVelocityController
     joint: right_front_to_base_link_joint
     pid: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 10.0}

  joint_left_front_base_link_wheel_controller:
     type: effort_controllers/JointVelocityController
     joint: left_front_to_base_link_joint
     pid: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 10.0}

  # joint_left_front_wheel_controller:
  #   type: effort_controllers/JointEffortController
  #   joint: joint_left_front_wheel
  #   pid: {p: 100.0, i: 0.01, d: 10.0}
  #
  # joint_left_rear_wheel_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: joint_left_rear_wheel
  #   pid: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 10.0}
  # joint_right_rear_wheel_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: joint_right_rear_wheel
  #   pid: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 10.0}
  #
  # joint_left_flipper_wheel_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint_left_flipper_wheel
  #   pid: {p: 1.0, i: 0.01, d: 1.0}
  # joint_right_flipper_wheel_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint_right_flipper_wheel
  #   pid: {p: 1.0, i: 0.01, d: 1.0}
